### ISSUE TITLE
intlpnIonic in ionic 2 version ?

### ISSUE THREAD

**Issue by mahmoudissmail** [pierre-vigier/intlpnIonic#10]
@pierre-vigier any update to ionic 2 for your library ?

**Comment by pierre-vigier** [comment]
Sorry, i missed that, nothing planned yet, but feel free to propose a pull request :)

**Comment by DilipNikam** [comment]
Is there any updated version available for iOnic2 ? Or any instruction to used this in iOnic2.

Pls let us know.

**Comment by pierre-vigier** [comment]
Still nothing planned, but for someone to recreate it on ionic 2 should not be too hard
