### ISSUE TITLE
Model value not persist on click

### ISSUE THREAD

**Issue by khushbukis** [pierre-vigier/intlpnIonic#11]
http://play.ionic.io/app/6d0a3832cc50

Above is link of demo you have provided.

When i click outside of textbox, my selected country code get disappeared. Any solution for this?

**Comment by pierre-vigier** [comment]
Actually, that is on purpose so the placeholder is there. When it's out of focus and there is just the country code, the flag is indicating the country, however, the field with display the placeholder.
