### ISSUE TITLE
Provider for config

### ISSUE THREAD

**Issue by alejandromagnorsky** [pierre-vigier/intlpnIonic#12]
It would be a great addition to have a provider (like the one in this repo https://github.com/hodgepodgers/ng-intl-tel-input) so we can specify for instance onlyCountry and utilsScript (to load it async like the original library).

Thanks. Great plugin!

**Comment by pierre-vigier** [comment]
I am not really sure on how to implement that, but if you submit a pull request, i'll be happy to merge it
