### ISSUE TITLE
Uneditable Country Code

### ISSUE THREAD

**Issue by baltejsingh88** [pierre-vigier/intlpnIonic#13]
I would like to know how can we make the country Code uneditable in field, after selecting the country.

**Comment by pierre-vigier** [comment]
right now we can't, it can probably be added, but it's not a trivial addition, feel free to propose a pull request with that

**Comment by pierre-vigier** [comment]
What about using national mode?
Like that you can select the country through the flag, but you the country code is not displayed

**Comment by pierre-vigier** [comment]
no feedback, so closing
