### ISSUE TITLE
How can I do mobile number validation?

### ISSUE THREAD

**Issue by Dineshrajaa** [pierre-vigier/intlpnIonic#16]
Hi all,
 How could I do validation while using this plugin, please help to do it..thanks in advance!
ps:
I read the documentation it's says ng-model will be updated only on entering valid number..
so can how can I use ng-messages to show appropriate message for this?

**Comment by pierre-vigier** [comment]
The validation is using the following library [libphonenumber](https://github.com/googlei18n/libphonenumber) from google, so i guess you could search in that direciton

**Comment by Dineshrajaa** [comment]
Thanks @pierre-vigier will check this and for now I am closing the Issue.

**Comment by pierre-vigier** [comment]
Welcome
