### ISSUE TITLE
Suport for Ionic 2.0

### ISSUE THREAD

**Issue by walfridosp** [pierre-vigier/intlpnIonic#17]
Hi there, 
I have been using this plugin and so far so good, now I'm using Ionic 2.0 but it doesn't work with this new version, is this something you are working on?
Thanks

**Comment by pierre-vigier** [comment]
I'm am not working on anything for ionic 2, but if you get all the validation code, it should not be too hard to adapt. I never worked with ionic2 yet, but creating a component for ionic 2 should actually simplify the code
