### ISSUE TITLE
ng-model value not available

### ISSUE THREAD

**Issue by Djokx** [pierre-vigier/intlpnIonic#18]
Hi,
Thank you for your module but I've some issues for getting the value of the input.

Even on your example, [http://play.ionic.io/app/6d0a3832cc50](http://play.ionic.io/app/6d0a3832cc50) nothing appears in front of Phone number entered for me. I noticed that the ng-model of the input is always "phone", is that normal ?

Well, I need to get the value of the input in my controller but I can't ? Is that an issue or I'm just doing it wrong ? 

Thanks

**Comment by pierre-vigier** [comment]
The value will appear only once you have a valid phone number, there's a validation before.
For instance, in the example, on the top one, if you enter: +33412341234 you will the the phone number, however, if you have one digit less, it will not work
