### ISSUE TITLE
get country code 

### ISSUE THREAD

**Issue by brtn86** [pierre-vigier/intlpnIonic#2]
Hi Pierre,

great work on this plugin! Is there any way to obtain the selected country code? E.g. if France is selected I'd like to have some way to access only the "+33" part of the full number.

Cheers
Ben

**Comment by pierre-vigier** [comment]
Hi Ben,

it's not yet possible, how would you see that? With a new attribute binding?

Cheers

**Comment by brtn86** [comment]
Yes, exactly. Maybe something like:

`<intlpn ng-model="connect.telNumber" country-code="connect.countryCode"...>`

**Comment by pierre-vigier** [comment]
Hi Ben,

done in version 0.1.3 , there are now 2 additional attributes country-iso-code and country-dial-code. Those 2 attributes are read only, and updated from the directive. meaning that, if you change the value of a variable bound to those attributes, the directive will not reflect any changes. However, if you use the directive to change country, those variables will be updated.

Cheers,

Pierre

**Comment by brtn86** [comment]
Wow, that was quick. Thanks a lot, man. Let me know if you ever make your way to Hamburg and I'll buy you a beer!

**Comment by pierre-vigier** [comment]
Welcome, actually, it was pretty easy to implement. It's working fine in my tests
