### ISSUE TITLE
Return null for bad input instead of undefined?

### ISSUE THREAD

**Issue by marko1943** [pierre-vigier/intlpnIonic#21]
Is there a way to do this?

Cant find it in a code...

edit: 
I just noticed this, I'll test it out
https://github.com/pierre-vigier/intlpnIonic/releases/tag/0.1.9

Your readme.md suggests that we install 0.1.8. through bower

**Comment by marko1943** [comment]
I just check 0.1.9. version and it has a bug 

> ionic.bundle.js:26799 TypeError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': 2 arguments required, but only 1 present.
    at intlpnIonic.js:368
    at Scope.$eval (ionic.bundle.js:30400)
    at Scope.$apply (ionic.bundle.js:30500)
    at HTMLInputElement.<anonymous> (intlpnIonic.js:365)
    at defaultHandlerWrapper (ionic.bundle.js:16792)
    at HTMLInputElement.eventHandler (ionic.bundle.js:16780)
    at tapHandleFocus (ionic.bundle.js:3138)
    at tapClick (ionic.bundle.js:2945)
    at HTMLDocument.tapTouchEnd (ionic.bundle.js:3069)

You can recreate it with this code for example:
`                <intlpn ng-model="model3" placeholder="Placeholder" default-country="gb" ></intlpn>
                <button ng-click="number(model3)" class="button button-assertive" ng-disabled="!model3">Print</button>
                <div class="item item-text-wrap">
                    Phone number entered: {{model3}}
                </div>`

**Comment by alejandromagnorsky** [comment]
Actually, it's really simple to reproduce this issue. Just use:
`<intlpn ng-model="user.mobile"></intlpn>`

**Comment by pierre-vigier** [comment]
Hi All,

fixed in 0.1.11
