### ISSUE TITLE
9 digits in Brazil

### ISSUE THREAD

**Issue by meredyk** [pierre-vigier/intlpnIonic#22]
In Brazil there are phones with up to 9 digits. Is it possible to include this in the validation of the number?

Tnx

**Comment by pierre-vigier** [comment]
The selector is relying on google liphoneutils, so if the google lib has
been updated to take them into account, it should work, you can replace the
lib files

**Comment by pierre-vigier** [comment]
i just released version 0.1.10 with an updated version of the number utils. It's now working with Brazilian 9 digits mobile phones
