### ISSUE TITLE
Select country, input.focus fail.

### ISSUE THREAD

**Issue by rodrigobarrocal** [pierre-vigier/intlpnIonic#5]
Focus fail... i do this.

 selectCountry: function(country) {
                        scope.isocode = country.iso2;
                        scope._updateDialCode(country.dialCode);
                        scope.modal.hide();
                        $timeout(
                            function() {
                                var input = element[0].querySelector('input');
                                input.focus();
                                var tmpStr = input.value;
                                input.value = '';
                                input.value = tmpStr;
                            }
                        );
                    },

**Comment by pierre-vigier** [comment]
Hi,

I'm sorry, but i do not understand the issue, what are you trying to do? What is failing?

**Comment by pierre-vigier** [comment]
I think i got it, thanks! SHould be fixed in 0.1.4
