### ISSUE TITLE
Input bind focus setSelection fail...

### ISSUE THREAD

**Issue by rodrigobarrocal** [pierre-vigier/intlpnIonic#6]
On focus the set selection fail. and i do this.

input.bind('focus', function() {
                        if (scope.national) {} else {
                            if (!scope.phone) {
                                scope.$apply(function() {
                                    scope.phone = scope.dialCode;
                                    $timeout(
                                        function() {
                                            input[0].setSelectionRange(scope.dialCode.length + 1, scope.dialCode.length + 1);
                                        }
                                    );
                                });
                            }
                        }
                    })

**Comment by pierre-vigier** [comment]
Same thing, no sure to understand? I am using that directive in some project, and i do not see focus issue, however, i might just not understand the problem you are facing

**Comment by pierre-vigier** [comment]
I think i got it, thanks! SHould be fixed in 0.1.4

**Comment by pierre-vigier** [comment]
Something strange here, it's within the $apply, why would we need a timeout?
